alias: Stop Electricty Selling
description: >-
  When battery charge drops below 51% or the feed-in price drops below 20c and
  the battery is in sell mode, then switch back to regular mode
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.esy_sunhome_battery_state_of_charge
    below: 51
  - trigger: numeric_state
    entity_id:
      - sensor.home_feed_in_price
    for:
      hours: 0
      minutes: 0
      seconds: 10
    below: 0.2
conditions:
  - condition: state
    entity_id: select.esy_sunhome_operating_mode
    state: Electricity Sell Mode
actions:
  - action: select.select_option
    target:
      entity_id: select.esy_sunhome_operating_mode
    data:
      option: Regular Mode
  - action: notify.mobile_app_sm_s938b
    metadata: {}
    data:
      message: Switched to regular mode
      title: Battery mode update
mode: single

#############################################################################

alias: Stop Charging
description: >-
  When battery charge drops is above 75% or the general price is above 9c and
  the battery is in buy mode, then switch back to regular mode
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.esy_sunhome_battery_state_of_charge
    above: 75
  - trigger: numeric_state
    entity_id:
      - sensor.home_general_price
    for:
      hours: 0
      minutes: 0
      seconds: 10
    above: 0.09
conditions:
  - condition: state
    entity_id: select.esy_sunhome_operating_mode
    state: Battery Energy Management
actions:
  - action: select.select_option
    target:
      entity_id: select.esy_sunhome_operating_mode
    data:
      option: Regular Mode
  - action: notify.mobile_app_sm_s938b
    metadata: {}
    data:
      message: Stopped Charging
mode: single

#############################################################################

alias: Energy Cost Half Hourly
description: >-
  Calculates the net charge for each half hour and adds it to lifetime energy
  charge.
triggers:
  - trigger: time_pattern
    minutes: /30
conditions: []
actions:
  - action: input_number.set_value
    target:
      entity_id: input_number.lifetime_energy_charge
    metadata: {}
    data:
      value: "{{ states('number.half_hourly_accumulating_charge') | float(0) }}"
mode: single

#############################################################################

alias: Energy Daily Access Charges
description: >-
    Adds the daily access charge and amber fee to the lifetime energy charge sensor"
triggers:
  - trigger: time_pattern
    hours: "0"
    minutes: "0"
    seconds: "1"
conditions: []
actions:
  - action: input_number.set_value
    target:
      entity_id: input_number.lifetime_energy_charge
    metadata: {}
    data:
      value: "{{ states('input_number.lifetime_energy_charge') | float(0) + 0.9790 }}"
  - action: input_number.set_value
    metadata: {}
    data:
      value: >
        {% set dt = now() %} 

        {% set days_this_month = (dt.replace(month=dt.month % 12 + 1, day=1) -
        timedelta(days=1)).day %} 

        {% set charge = (12.5/days_this_month) | float(0) %}

        {{ states('input_number.lifetime_energy_charge') | float(0) + charge }}
    target:
      entity_id: input_number.lifetime_energy_charge
mode: single
