- platform: integration
  source: sensor.esy_sunhome_battery_import
  name: Energy To Battery
  unique_id: energy_to_battery
  unit_prefix: k
  round: 2
  method: left
  max_sub_interval:
    minutes: 1

- platform: integration
  name: Energy From Solar
  unique_id: energy_from_solar
  source: sensor.esy_sunhome_pv_power
  unit_prefix: k
  round: 2
  method: left
  max_sub_interval:
    minutes: 1

- platform: integration
  name: Energy From Battery
  unique_id: energy_from_battery
  source: sensor.esy_sunhome_battery_export
  unit_prefix: k
  round: 2
  method: left
  max_sub_interval:
    minutes: 1

- platform: integration
  name: Energy From Grid
  unique_id: energy_from_grid
  source: sensor.esy_sunhome_grid_import
  unit_prefix: k
  round: 2
  method: left
  max_sub_interval:
    minutes: 1

- platform: integration
  name: Energy To Grid
  unique_id: energy_to_grid
  source: sensor.esy_sunhome_grid_export
  unit_prefix: k
  round: 2
  method: left
  max_sub_interval:
    minutes: 1

- platform: integration
  name: Energy To Home
  unique_id: energy_to_home
  source: sensor.esy_sunhome_load_power
  unit_prefix: k
  round: 2
  method: left
  max_sub_interval:
    minutes: 1
