# -------------------------
# TEMPLATE ENTITIES
# -------------------------
template:
  - sensor:
        # Current Rate is the rate descriptor
      - name: "Current Rate"
        unique_id: 01JSJ961WXK9QCB3RM7KFJ8CA4
        icon: mdi:meter-electric-outline
        state: >
            {% if states('sensor.home_general_price_descriptor') not in ['unavailable', 'unknown', 'none'] %}
              {{ states('sensor.home_general_price_descriptor').replace('_', ' ') | title }}
            {% else %}
              {{ this.state }}
            {% endif %}
      - name: "Current Charge"
        unique_id: 01JSJ9HDRYPPTWZKJ39FJN1JJH
        icon: mdi:meter-electric
        unit_of_measurement: "$"
        state: >
            {% if states('sensor.home_general_price') not in ['unavailable', 'unknown', 'none'] %}
              {{ states('sensor.home_general_price') }} 
            {% else %}
              {{ this.state }}
            {% endif %}
      - name: "Current Export Rate"
        # Current Export Rate is the Descriptor
        unique_id: 01K2K91A63BK2XJP3PPV03K66W
        state: >
            {% if states('sensor.home_feed_in_price_descriptor') not in ['unavailable', 'unknown', 'none'] %}
              {{ states('sensor.home_feed_in_price_descriptor').replace('_', ' ') | title }}
            {% else %}
              {{ this.state }}
            {% endif %}

  - number:
      # Half Hourly Accumulating Charge
      - name: "Half Hourly Accumulating Charge"
        unique_id: 01JWVVB9QHP5QGNVTWP67VEB72
        unit_of_measurement: "$"
        min: 0
        max: 100
        step: 1
        state: >
            {% set consumption = states('sensor.half_hour_max_import') | float(0) %}
            {% set production = states('sensor.half_hour_max_export') | float(0) %}
            {% set energy = consumption - production | float(0) %}
            {% set rate = states('sensor.current_charge') | float(0) %}
            {% set export_rate = states('number.current_export_charge') | float(0) %}
            {% if energy > 0 %}
              {{ (states('input_number.lifetime_energy_charge') | float(0)) + (energy * rate) }}
            {% else %}
              {{ (states('input_number.lifetime_energy_charge') | float(0)) + (energy * export_rate) }}
            {% endif %}

  - number:
      # Current Export Charge
      - name: "Current Export Charge"
        unique_id: 01K2K8FGHKB8H12RPE7NJB3CGT
        unit_of_measurement: "$"
        min: 0
        max: 100
        step: 1
        state: >
            {% if states('sensor.home_feed_in_price') not in ['unavailable', 'unknown', 'none'] %}
              {{ states('sensor.home_feed_in_price') }} 
            {% else %}
              {{ this.state }}
            {% endif %}

# -------------------------
# STATISTICS SENSORS
# -------------------------
sensor:
  # Half Hour Max Consumption (max over last 30 minutes)
  - platform: statistics
    name: "Half Hour Max Consumption"
    unique_id: 01JWVSZQDGE6RWNK7YYJ7TN7DE
    entity_id: sensor.consumption_half_hourly
    state_characteristic: value_max
    max_age:
      minutes: 30

  # Half Hour Max Production
  - platform: statistics
    name: "Half Hour Max Production"
    unique_id: 01JWVT1R5H5JP7SNDQ928A5X2S
    entity_id: sensor.production_half_hourly
    state_characteristic: value_max
    max_age:
      minutes: 30

  # Half Hour Max Export
  - platform: statistics
    name: "Half Hour Max Export"
    unique_id: 01K2PKKVJY1TXTPWVAEAEKNGVA
    entity_id: sensor.export_half_hourly
    state_characteristic: value_max
    max_age:
      minutes: 30

  # Half Hour Max Import
  - platform: statistics
    name: "Half Hour Max Import"
    unique_id: 01K2PKP0GPBDG2C8M9FEDPSZN1
    entity_id: sensor.import_half_hourly
    state_characteristic: value_max
    max_age:
      minutes: 30

# -------------------------
# FILTERED (ROLLING) SENSORS
# -------------------------
sensor:
  # Home Battery Export Rolling Average (time-based SMA example)
  - platform: filter
    name: "Home Battery Export Rolling Average"
    unique_id: 01K2CKT99F88XACNM0HKB9DKMD
    entity_id: sensor.esy_sunhome_battery_export
    filters:
      - filter: time_simple_moving_average
        window_size: "00:30"
        precision: 0

  # Solar Production EMA (low-pass = exponential smoothing)
  - platform: filter
    name: "Solar Production EMA"
    unique_id: 01K2D9V7ZMYNPT51N4TE9AA0M5
    entity_id: sensor.esy_sunhome_pv_power
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 0
